learning_log/learning_log/urls.py
from django.contrib import admin
from django.urls import path, include
urlpatterns = [
 path('admin/', admin.site.urls),
 path('users/', include('users.urls')),
 path('', include('main.urls')),
]

learning_log/main/urls.py
from django.urls import path
from . import views
#"""Определяет схемы URL для learning_logs."""

app_name = 'main'
urlpatterns=[
    path('', views.index, name='index'),
    path('topics/', views.topics, name='topics'),
    path('topics/<int:topic_id>/', views.topic, name='topic'),
    path('new_topic/', views.new_topic, name='new_topic'),
    path('new_entry/<int:topic_id>/', views.new_entry, name='new_entry'),
    path('edit_entry/<int:entry_id>/', views.edit_entry, name='edit_entry'),

]

learning_log/users/urls.py
from django.urls import path, include
from . import views

app_name = 'users'
urlpatterns = [
 # Включить URL авторизации по умолчанию.
 path('', include('django.contrib.auth.urls')),
 # Страница регистрации.
 path('register/', views.register, name='register'),
]

learning_log/main/models.py
from django.db import models
from django.contrib.auth.models import User


class Topic(models.Model):
    """Тема, которую изучает пользователь"""

    text = models.CharField(max_length=200)
    date_added = models.DateTimeField(auto_now_add=True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)



    def __str__(self):
        """Возвращает строковое представление модели."""
        return self.text


class Entry(models.Model):
    """Информация, изученная пользователем по теме"""

    topic = models.ForeignKey(Topic, on_delete=models.CASCADE)
    text = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = 'entries'

    def __str__(self):
        """Возвращает строковое представление модели."""

        if {self.text} <= {self.text[:50]}:
            return f"{self.text[:50]}"
        else:
            return f"{self.text[:50]}..."

learning_log/users/models.py
from django.db import models

# Create your models here.

learning_log/main/forms.py
from django import forms

from .models import Topic, Entry



class TopicForm(forms.ModelForm):
    class Meta:

        model = Topic
        fields = ['text']
        labels = {'text': ''}


class EntryForm(forms.ModelForm):
    class Meta:
        model = Entry
        fields = ['text']
        labels = {'text': 'Entry:'}
        widgets = {'text': forms.Textarea(attrs={'cols': 80})}

learning_log/main/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from .models import Topic, Entry
from .forms import TopicForm, EntryForm
from django.http import Http404


def index(request):
    """Домашняя страница приложения Learning Log"""
    return render(request, 'main/index.html')


@login_required
def topics(request):
    """Выводит список тем."""
    topics = Topic.objects.filter(owner=request.user).order_by('date_added')
    context = {'topics': topics}
    return render(request, 'main/topics.html', context)


@login_required
def topic(request, topic_id):
    """Выводит одну тему и все ее записи."""
    topic = get_object_or_404(Topic, id=topic_id)
    if topic.owner != request.user:
        raise Http404
    entries = topic.entry_set.order_by('-date_added')
    context = {'topic': topic, 'entries': entries}
    return render(request, 'main/topic.html', context)


@login_required
def new_topic(request):
    if request.method != 'POST':
 # Данные не отправлялись; создается пустая форма.
        form = TopicForm()
    else:
 # Отправлены данные POST; обработать данные.
        form = TopicForm(data=request.POST)
        if form.is_valid():
            new_topic = form.save(commit=False)
            new_topic.owner = request.user
            new_topic.save()
            return redirect('main:topics')
 # Вывести пустую или недействительную форму.
    context = {'form': form}
    return render(request, 'main/new_topic.html', context)


@login_required
def new_entry(request, topic_id):
    topic = get_object_or_404(Topic, id=topic_id)

    if request.method != 'POST':
            # Данные не отправлялись; создается пустая форма.
        form = EntryForm()
    else:
            # Отправлены данные POST; обработать данные.
        form = EntryForm(data=request.POST)
        if form.is_valid():
            new_entry = form.save(commit=False)
            new_entry.topic = topic
            new_entry.save()
            return redirect('main:topic', topic_id=topic_id)

        # Вывести пустую или недействительную форму.
    context = {'topic': topic, 'form': form}
    return render(request, 'main/new_entry.html', context)


@login_required
def edit_entry(request, entry_id):
    entry = get_object_or_404(Entry,id=entry_id)
    topic = entry.topic
    if topic.owner != request.user:
        raise Http404
    if request.method != 'POST':
        # No data submitted; create a blank form
        form = EntryForm(instance=entry)
    else:
        # Post data submitted;process data
        form = EntryForm(request.POST, instance=entry)
        if form.is_valid():
            form.save()
            return redirect('main:topic',topic_id=topic.id)


    context = {'entry': entry, 'topic': topic, 'form': form}
    return render(request, 'main/edit_entry.html', context)

learning_log/users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm



def register(request):
    """Регистрирует нового пользователя."""


    if request.method != 'POST':
# Выводит пустую форму регистрации.
        form = UserCreationForm()
    else:
# Обработка заполненной формы.
       form = UserCreationForm(data=request.POST)

       if form.is_valid():
           new_user = form.save()
# Выполнение входа и перенаправление на домашнюю страницу.
           login(request, new_user)
           return redirect('main:index')

# Вывести пустую или недействительную форму.
    context = {'form': form}
    return render(request, 'users/register.html', context)

learning_log/main/templates/main/base.html
{% load bootstrap4 %}

<!doctype html>
<html lang="en">
<head>
 <meta charset="utf-8">
 <meta name="viewport" content="width=device-width, initial-scale=1,
 shrink-to-fit=no">
    <title>Learning Log</title>

{% bootstrap_css %}
{% bootstrap_javascript jquery='full' %}

</head>
 <body>
    <nav class="navbar navbar-expand-md navbar-light bg-light mb-4 border">
        <a class="navbar-brand" href="{% url 'main:index'%}">
        Learning Log</a>

        <button class="navbar-toggler" type="button" data-toggle="collapse"
            data-target="#navbarCollapse" aria-controls="navbarCollapse"
            aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span></button>
            <div class="collapse navbar-collapse" id="navbarCollapse">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'main:topics'%}">
                            Topics</a>
                    </li>
                </ul>
                <ul class="navbar-nav ml-auto">
                    {% if user.is_authenticated %}
                        <li class="nav-item">
                            <span class="navbar-text"}>Hello, {{ user.username }}.</span>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'users:logout' %}">Log out</a>
                        </li>
                     {% else %}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'users:register' %}">Register</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'users:login' %}">Log in</a></li>
                    {% endif %}
                </ul>
            </div>

    </nav>
    <main role="main" class="container">
        <div class="pb-2 mb-2 border-bottom">
            {% block page_header %}{% endblock page_header %}
        </div>
        <div>
            {% block content %}{% endblock content %}
        </div>
    </main>
 </body>
</html>

learning_log/main/templates/main/edit_entry.html
{% extends "main/base.html" %}
 {% load bootstrap4 %}

{% block page_header %}
 <h2>Edit entry</h2>
{% endblock page_header %}

{% block content %}
<h3><a href="{% url 'main:topic' topic.id%}">{{ topic }}</a></h3>>


<form method="post" action="{% url 'main:edit_entry' entry.id %}" class="form">
    {% csrf_token %}
    {% bootstrap_form form %}
    {% buttons %}
     <button name="submit" class="btn btn-primary">Edit entry</button>
    {% endbuttons %}
 </form>
{% endblock content %}

learning_log/main/templates/main/index.html
{% extends "main/base.html" %}


{% block page_header %}
    <div class='jumbotron'>
        <h1 class="display-3">Blog.</h1>
        <p class="lead">A blog (a truncation of "weblog") is a discussion or informational website published on the World Wide Web 
            consisting of discrete, often informal diary-style text entries (posts) :)</p>
        <a class="btn btn-lg btn-primary" href="{% url 'users:register' %}"
            role="button">Register &raquo;</a>
    </div>
{% endblock page_header %}

learning_log/main/templates/main/new_entry.html
{% extends "main/base.html" %}
 {% load bootstrap4 %}

{% block page_header %}
 <h2>Entry</h2>
{% endblock page_header %}

{% block content %}
 
    <h3><a href="{% url 'main:topic' topic.id %}">{{ topic }}</a></h3>

    <form method="post" action="{% url 'main:new_entry' topic.id %}" class="form">
    {% csrf_token %}
    {% bootstrap_form form %}
    {% buttons %}
     <button name="submit" class="btn btn-primary">Add a new entry</button>
    {% endbuttons %}
 </form>
 
{% endblock content %}

learning_log/main/templates/main/new_topic.html
{% extends "main/base.html" %}
{% load bootstrap4 %}


{% block page_header %}
 <h2>Topic</h2>
{% endblock page_header %}


{% block content %}

 <form method="post" action="{% url 'main:new_topic' %}" class="form">
    {% csrf_token %}
    {% bootstrap_form form %}
    {% buttons %}
     <button name="submit" class="btn btn-primary">Add a new topic</button>
    {% endbuttons %}
 </form>

{% endblock content %}

learning_log/main/templates/main/topic.html
{% extends "main/base.html" %}

{% block page_header %}
 <h3>{{ topic }}</h3>
{% endblock page_header %}

{% block content %}

    <p>
        <h4><a  href="{% url 'main:new_entry' topic.id %}"> add new entry</a></h4>
    </p>
     {% for entry in entries %}
     <div class="card mb-3">
        <h4 class="card-header">
            {{ entry.date_added|date:'M d, Y H:i' }} ,
            <small><a href="{% url 'main:edit_entry' entry.id %}">
                 edit entry</a></small>
        </h4>
        <div class="card-body">
            {{ entry.text|linebreaks }}
        </div>
     </div>
    {% empty %}
        <p>There are no entries for this topic yet.</p>
    {% endfor %}


{% endblock content %}

learning_log/main/templates/main/topics.html
{% extends "main/base.html" %}

{% block page_header %}
 <h1>Topics</h1>
{% endblock page_header %}




{% block content %}


    <ul>
     {% for topic in topics %}
        <li><h3>
            <a href="{% url 'main:topic' topic.id %}">{{ topic }}</a>
        </h3></li>
     {% empty %}
        <li><h3>No topics have been added yet.</h3></li>
     {% endfor %}
    </ul>
    <h3><a href="{% url 'main:new_topic' %}">Add a new topic</a></h3>

{% endblock content %}

learning_log/users/templates/users/register.html
{% extends "main/base.html" %}
{% load bootstrap4 %}

{% block page_header %}
 <h2>Register</h2>
{% endblock page_header %}



{% block content %}
<form method="post" action="{% url 'users:register' %}" class="form">
    {% csrf_token %}
    {% bootstrap_form form %}
    {% buttons %}
     <button name="submit" class="btn btn-primary">Register</button>
    {% endbuttons %}
 </form>

{% endblock content %}